-- =====================================================================
-- FILE 01: KHỞI TẠO CẤU TRÚC CƠ SỞ DỮ LIỆU (SCHEMA)
-- =====================================================================

CREATE DATABASE IF NOT EXISTS datafrontiers_journal_db;
USE datafrontiers_journal_db;

-- DỌN SẠCH CÁC BẢNG CŨ THEO ĐÚNG THỨ TỰ RÀNG BUỘC (Tránh lỗi khóa ngoại)
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS REVIEW_ASSIGNMENT;
DROP TABLE IF EXISTS REVIEWER_FIELD;
DROP TABLE IF EXISTS SUBMISSION_AUTHOR;
DROP TABLE IF EXISTS SUBMISSION;
DROP TABLE IF EXISTS EXPERTISE_FIELD;
DROP TABLE IF EXISTS REVIEWER;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS ISSUE;
SET FOREIGN_KEY_CHECKS = 1;

-- TIẾN HÀNH TẠO MỚI CÁC BẢNG TRONG HỆ THỐNG
CREATE TABLE ISSUE (
    IssueID INT AUTO_INCREMENT,
    Volume INT NOT NULL,
    Number INT NOT NULL,
    Quarter INT NOT NULL,
    PublishYear INT NOT NULL,
    PublishDate DATE NULL,
    Title VARCHAR(200) NOT NULL,
    Status VARCHAR(20) DEFAULT 'Draft',
    PRIMARY KEY (IssueID)
) ENGINE=InnoDB;

CREATE TABLE AUTHOR (
    AuthorID INT AUTO_INCREMENT,
    FullName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Phone VARCHAR(20) NULL,
    Affiliation VARCHAR(200) NULL,
    PRIMARY KEY (AuthorID)
) ENGINE=InnoDB;

CREATE TABLE REVIEWER (
    ReviewerID INT AUTO_INCREMENT,
    FullName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Institution VARCHAR(200) NULL,
    AcademicDegree VARCHAR(100) NULL,
    PRIMARY KEY (ReviewerID)
) ENGINE=InnoDB;

CREATE TABLE EXPERTISE_FIELD (
    FieldID INT AUTO_INCREMENT,
    FieldName VARCHAR(100) NOT NULL,
    Description TEXT NULL,
    PRIMARY KEY (FieldID)
) ENGINE=InnoDB;

CREATE TABLE SUBMISSION (
    SubmissionID INT AUTO_INCREMENT,
    IssueID INT NULL,
    Title VARCHAR(300) NOT NULL,
    Abstract TEXT NULL,
    Keywords VARCHAR(300) NULL,
    SubmitDate DATE NOT NULL,
    Status VARCHAR(30) DEFAULT 'Submitted',
    PRIMARY KEY (SubmissionID),
    CONSTRAINT fk_submission_issue FOREIGN KEY (IssueID) REFERENCES ISSUE(IssueID) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE SUBMISSION_AUTHOR (
    SubmissionID INT,
    AuthorID INT,
    AuthorOrder INT NOT NULL,
    PRIMARY KEY (SubmissionID, AuthorID),
    CONSTRAINT fk_sub_auth_submission FOREIGN KEY (SubmissionID) REFERENCES SUBMISSION(SubmissionID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_sub_auth_author FOREIGN KEY (AuthorID) REFERENCES AUTHOR(AuthorID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE REVIEWER_FIELD (
    ReviewerID INT,
    FieldID INT,
    PRIMARY KEY (ReviewerID, FieldID),
    CONSTRAINT fk_rev_field_reviewer FOREIGN KEY (ReviewerID) REFERENCES REVIEWER(ReviewerID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_rev_field_domain FOREIGN KEY (FieldID) REFERENCES EXPERTISE_FIELD(FieldID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE REVIEW_ASSIGNMENT (
    AssignmentID INT AUTO_INCREMENT,
    SubmissionID INT NOT NULL,
    ReviewerID INT NOT NULL,
    AssignedDate DATE NOT NULL,
    DueDate DATE NULL, -- Đã sửa thành NULL để Trigger hoạt động bắt giá trị trống
    CompletedDate DATE NULL,
    Score INT NULL,
    Recommendation VARCHAR(50) NULL,
    Comments TEXT NULL,
    PRIMARY KEY (AssignmentID),
    CONSTRAINT fk_assignment_submission FOREIGN KEY (SubmissionID) REFERENCES SUBMISSION(SubmissionID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_assignment_reviewer FOREIGN KEY (ReviewerID) REFERENCES REVIEWER(ReviewerID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

-- Chạy lệnh bổ sung ràng buộc UNIQUE
USE datafrontiers_journal_db;

ALTER TABLE ISSUE 
ADD CONSTRAINT uk_issue_identity UNIQUE (Volume, Number, Quarter, PublishYear);